[package]
name = "rand_wikipedia"
version = "0.1.0"
authors = ["William Roe <git@wjlr.org.uk>"]

[dependencies]
reqwest = { version = "0.10", features = ["blocking"] }
scraper = "0.12"
rand = "0.7"
clap = "2.33"

[[bin]]
name = "rand_wikipedia"
doc = false
path = "src/main.rs"
